spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secureauth
    username: yacine
    password: joueur12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 28723060079-2h5maukbmeh517caou4ihmlc01jccgbr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: IMesriS9VAw0O5RS8hRRF8v2zGNSDG5ZpjiAwnmdEOmbzZyVIFQDXrQU_TkaSR4LKenf1hRwuIJsU6-q00TqaQ
  expiration: 1200000
  refresh-expiration: 604800000
